### ISSUE TITLE
Request: Add another Feature to description

### ISSUE THREAD

**Issue by dagaz** [anton-arnold/xoverrideheadphonejackdetection#4]
This Module works also fine as a solution for another realy nasty problem:

Many Phones (my is a Oneplus 7 Pro) without a 3,5mm audio jack recognise a 3,5mm-Jack-Headset with USB-adapter as an external audiospeaker. The result is a very strong echo for the other side of a phone call.

This Module solves not only broken audio jacks but also this USB-Adapter problem.

It would be nice if you coud add it to the description, so that other users can find it as a solution for their Problems, too.

**Comment by anton-arnold** [comment]
@dagaz thanks for the information. I updated the usecases in the readme sections.
