### ISSUE TITLE
Not Working OnePlus 5t Pie

### ISSUE THREAD

**Issue by HotLungs** [anton-arnold/xoverrideheadphonejackdetection#5]
Hi, thank you for sharing the module, I've been looking for something like this for a while. 

Unfortunately, it's not working on my OnePlus 5t on stock Oxygen OS (Android 9.0.10). I'm using the latest EdXposed Sandhook beta and Magisk 20.3. I would reboot with headset plugged/unplugged and try different connection states and hybrid mode on/off but nothing changes. 

Could the module be conflicting with the viper4android(2.7.1.0) I have installed? 

Here are my module logs:
[xposed_all_20200201_004041.log](https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/4140628/xposed_all_20200201_004041.log)
[xposed_error_20200201_004030.log](https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/4140622/xposed_error_20200201_004030.log)

**Comment by anton-arnold** [comment]
@iLumic are you sure your EdXposed modules are running at all? The log is quite empty, you can take a look at the log poste in issue #3: https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/3908318/EdXposed_Verbose_all_20191201_095213.log
This module is logging quite much, even at the initialization, and there a no log messages.
Also your sandhook beta is not the latest, can you try 0.4.6.0_beta - see https://github.com/ElderDrivers/EdXposed/releases

**Comment by HotLungs** [comment]
@anton-arnold I just updated EdXposed to 0.4.6.1 and magisk to 20.4 (both canary since 0.4.6.0 bootlooped). I made sure other xposed modules are working, it seems it's just xoverideheadphonejackdetection that's not. 

Here are the verbose EdXposed logs: 
[EdXposed_Verbose_20200201_183102.log](https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/4142431/EdXposed_Verbose_20200201_183102.log)

**Comment by anton-arnold** [comment]
@iLumic ok it seems that this module is not compatible with viper4android.
The logs indicate that either the class com.android.server.WiredAccessoryManager or its method notifyWiredAccessoryChanged cannot be found which havn't been touched by google for quite some years. The viper4android core module seems to be closed source and I can't take a look if compatibility could be realized with low effort. You'd have to ask there if you like this modules functionality to be realized within viper4android.
